### ISSUE TITLE
Allow empty attributes

### ISSUE THREAD

**Issue by arnoson** [fabianmichael/kirby-template-attributes#3]
Right now empty attributes are only added if they don't have a value:
```php
attributes(['alt']);
```
Would be great if this also works (but it seems to be filtered out):
```php
attributes(['alt' => '']);
```
I prefer the first syntax, but in some cases I can only use the second (e.g. auto-generated attributes that have to be an associative array).

**Comment by fabianmichael** [comment]
@arnoson I’ve finally had a look at this because it bugs me as well. Since this plugin uses Kirby’s attribute renderer and I don’t want to implement my own that behaves differently, we have to wait until Kirby updates its behavior, see: https://github.com/getkirby/kirby/blob/4.0.0-rc.2/src/Toolkit/Xml.php#L97

**Comment by arnoson** [comment]
thanks for looking into this! Good to know that it is on kirby's todo-list :)

**Comment by fabianmichael** [comment]
@arnoson Kirby 4 finally fixed the empty attribute behavior last minute. I’ve drafted a new release and added a corresponding unit test for the new expected behavior.

https://github.com/fabianmichael/kirby-template-attributes/releases/tag/2.0.0
